config/routes.rb
Rails.application.routes.draw do


  resources :books, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image

  belongs_to :user


validates :title, presence: true
validates :body,
     presence: true, length: {maximum: 200}



end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :profile_image

  has_many :books, dependent: :destroy

  validates :name,
     length: {minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,
     length: {maximum: 50}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize: size).processed
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :congigure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
     user_path(current_user[:id])
  end

  def after_sign_out_path_for(resource)
    flash[:notice]
    root_path
  end

  protected

  def congigure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])


  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if@book.save
    flash[:notice] = "You have created book successfully."
    redirect_to action: "show", id: @book
   else
    @books = Book.all
    @user = User.find(current_user[:id])
    render :index


   end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new


  end

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to action: "index"
    else
    @book = Book.find(params[:id])
    end
  end

  def update
    @book = Book.find(params[:id])
    if@book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)

  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @book = Book.new
  end

  def show
   @book = Book.new
   @user = User.find(params[:id])
   @books = @user.books
   

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if@book.save
     flash[:notice] = "You have created book successfully."
     redirect_to action: "show", id: @book
     else
      @books = Book.all
      @user = User.find(current_user[:id])
      render :index
     end
  end

  def index
    @book = Book.new
    @user = User.find(current_user[:id])
    @users = User.all
    @books = Book.all


  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to action: "show", id: current_user.id
    else
      @user = User.find(params[:id])
    end
  end

  def update
    @user = User.find(params[:id])
    if@user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to action: "show", id: @user
    else
     render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)

  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_leftside.html.erb
<div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
         <tr>
           <th><%= image_tag @user.get_profile_image("63x63") %></th>
           <th></th>
         </tr>

         <tr>
           <th>name</th>
           <th><%= @user.name %></th>
         </tr>

         <tr>
           <th>introduction</th>
           <th><%= @user.introduction %></th>
         </tr>

        </tbody>
      </table>
        <div class="row">
          <%= link_to edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
           <span class=""></span>
          <% end %>
        </div>
      <div>
       <h1>New book</h1>
       <%= form_with model: book, local: true do |f| %>
        <h4>Title</h4>
         <%= f.text_field :title %>
        <h4>Opinion</h4>
         <%= f.text_area :body %>
         <%= f.submit 'Create Book', class:"btn btn-success" %>
       <% end %>
       </div>
</div>

app/views/books/edit.html.erb
<div class = "container">

  <div class = "row">
    <div class = "col">
      <h1>Editing Book</h1>
      <div class="text-danger">
        <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
         <ul>
        <li><%= message %></li>
         </ul>
          <% end %>
         <% end %>
      </div>
      <%= form_with model: @book, local:true do |f| %>
       <label for="Title">Title</label>
       <P><%= f.text_field :title, autofocus: true, id:"Title", placeholder: @book.title %></p>
       <label for="Body">Opinion</label>
       <p><%= f.text_area :body, autofocus: true, id:"Body", placeholder: @book.body %></p>
       <%= f.submit"Update Book", class:"btn btn-success" %>
       <% end %>
       <%= link_to "Show", controller:"books", action:"show", id: @book %>
       |
       <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
 <div class="text-danger">
  <p></p>
   <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <% @book.errors.full_messages.each do |message| %>
    <ul><li><%= message %></li></ul>
    <% end %>
   <% end %>
   </div>
  <div class="row">
   <%= render partial:'leftside', locals:{ book: @book} %>
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table">
       <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
         </tr>
       </thead>
       <tbody>
         <% @books.each do |book| %>
         <tr>
           <td><%= link_to controller:"users", action:"show", id: (book.user_id) do %>
               <%= image_tag book.user.get_profile_image("40x40")  %>
            <% end %>
            </td>
           <td><%= link_to book.title, controller:"books", action:"show", id: book %></td>
           <td><%= book.body %></td>
         </tr>
       </tbody>
         <% end %>
     </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="text-success"><p><%= flash[:notice] %></p></div>
<div class="container">
  <div class="row">
   <%= render partial: 'books/leftside', locals: {book: @book_new} %>
    <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
     <table class="table table-hover table-inverse">
       <tbody>
         <tr>
           <td><%= link_to @book.user.name, controller:"users", action: "show", id: @book.user.id %>
             </td>
           <td><%= link_to @book.title, controller:"books", action: "show", id: @book %></td>
           <td><%= @book.body %></td>
           <% if @book.user == current_user %>
           <td><%= link_to "Edit", controller:"books", action: "edit", id: @book %></td>
           <td><%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' } %></td>
         </tr><% end %>
       </tbody>

     </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto mt-3">Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
      <p>In <strong>Bookers,</strong></p>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
       <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
       </div>
       <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
       </div>
      </div>
    </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/9c2b7fd351.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navber navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <div class="navbar-collapse">
        <div class="px-3">
           <%= link_to root_path do %>
           <span class="h5 text-light my-3">Bookers</span>
           <% end %>
        </div>
      <% if user_signed_in? %>
      <ul class="navbar-nav ml-auto px-2">
       <li class=>
         <%= link_to user_path(current_user.id) do %>
         <p class="h6 text-light my-3"><span class="fas fa-home"></span>Home</p>
         <% end %>
       </li>
       <li class="px-1">
         <%= link_to users_path do %>
         <p class= "h6 text-light my-3"><i class="fas fa-users"></i>Users</p>
         <% end %>
       </li>
       <li class="px-1">
         <%= link_to books_path do %>
         <p class="h6 text-light my-3"><span class="fas fa-book-open"></span>Books</p>
         <% end %>
       </li>
       <li class="px-1">
        <%= link_to  destroy_user_session_path, method: :delete do %>
        <p class="h6 text-light my-3"><span class="fas fa-sign-out-alt"></span>Log out</p>
        <% end %>
       </li>
      </ul>
      <% else %>
      <ul class="navbar-nav ml-auto">
       <li class="px-1">
         <%= link_to root_path do %>
         <p class="h6 text-light my-3"><span class="fas fa-home"></span>Home</p>
         <% end %>
       </li>
       <li class="px-1">
         <%= link_to about_path do %>
         <p class="h6 text-light my-3"><span class="fas fa-link"></span>About</p>
         <% end %>
       </li>
       <li class="px-1">
        <%= link_to new_user_registration_path do %>
        <p class="h6 text-light my-3"><span class="fas fa-user-plus"></span>Sign up</p>
        <% end %>
       </li>
       <li class="px-1">
        <%= link_to new_user_session_path do %>
        <p class="h6 text-light my-3"><span class="fas fa-sign-in-alt"></span>Log in</p>
        <% end %>
       </li>
      </ul>
      <% end %>
      </div>
    </div>
    </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <h1>User info</h1>
      <div class="text-danger">
        <% if @user.errors.any? %>
         <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
         <% @user.errors.full_messages.each do |message| %>
         <ul><li><%= message %></li></ul>
         <% end %>
        <% end %>
   </div>
      <%= form_with model: @user do |f| %>
      <div class="form_group">
      <label for="inputName">Name</label>
      <%= f.text_field :name,autofocus: true, id:"inputName",placeholder:"current_user.name" %>
      </div>
      <div class="form_group">
      <label for="inputImage">Image</label>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", acccept: "image/*" %>
      </div>
      <div class="form_group">
      <label for="inputIntroduction">Introduction</label>
      <%= f.text_area :introduction,autofocus: true, id:"inputIntroduction" %>
      </div>
      <div class="form_group">
      <%= f.submit"Update User" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <p></p>
  <div class="row">
    <%= render partial: 'books/leftside', locals: {book: @book} %>
    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table">
       <thead>
         <tr>
           <th>image</th>
           <th>name</th>
         </tr>
       </thead>
       <tbody>
         <% @users.each do |user| %>
         <tr>
           <td><%= image_tag user.get_profile_image("40x40") %></td>
           <td><%= user.name %></td>
           <td><%= link_to "Show", controller:"users", action: "show", id: user %></td>
         </tr>
       </tbody>
         <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-success"><p><%= flash[:notice] %></p></div>
<div class="container px-5 px-sm-0">
  <div class="row">
   <%= render partial: 'books/leftside', locals: {book: @book} %>
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table">
       <thead>
         <tr>
           <th>Title</th>
           <th>Opinion</th>
         </tr>
       </thead>
       <tbody>
         <% @books.each do |book| %>
         <tr>
           <td><%= link_to controller:"users", action:"show", id: (book.user_id) do %>
               <%= image_tag book.user.get_profile_image("40x40") %>
               <% end %>
           </td>
           <td><%= link_to book.title, controller:"books", action: "show", id: book %></td>
           <td><%= book.body %></td>
           <td></td>
           <td></td>
         </tr>
       </tbody>
         <% end %>
      </table>
    </div>
  </div>
</div>